version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vgcb8iKaZ8wnYYpYWU2G

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_DB: railway
      PMA_HOST: containers-us-west-84.railway.app
      PMA_PORT: 6145
      PMA_USER: root
      PMA_PASSWORD: vgcb8iKaZ8wnYYpYWU2G